export const productsData = [
  {
    name: "Men's T-shirt",
    description:
      "Comfortable cotton T-shirt with a round neck and short sleeves.",
    price: 19.99,
    slug: "mens-tshirt",
    isFeatured: true,
    image: "",
    category: "Clothes",
    stock: 120,
    brand: "FashionX",
    isActive: true,
    targetAudience: "Men",
  },
  {
    name: "Women's Blouse",
    description: "Elegant blouse with a v-neck and flowy sleeves.",
    price: 29.99,
    slug: "womens-blouse",
    isFeatured: false,
    image: "",
    category: "Clothes",
    stock: 80,
    brand: "ChicStyle",
    isActive: true,
    targetAudience: "Women",
  },
  {
    name: "Men's Running Shoes",
    description: "Breathable mesh shoes with cushioned soles for running.",
    price: 59.99,
    slug: "mens-running-shoes",
    isFeatured: false,
    image: "",
    category: "Footwear",
    stock: 200,
    brand: "StrideFit",
    isActive: true,
    targetAudience: "Men",
  },
  {
    name: "Women's Skinny Jeans",
    description: "High-waisted skinny jeans with a soft stretch fabric.",
    price: 49.99,
    slug: "womens-skinny-jeans",
    isFeatured: true,
    image: "",
    category: "Clothes",
    stock: 100,
    brand: "DenimCo",
    isActive: true,
    targetAudience: "Women",
  },
  {
    name: "Women's Sunglasses",
    description: "Stylish oversized sunglasses with UV protection.",
    price: 19.99,
    slug: "womens-sunglasses",
    isFeatured: true,
    image: "",
    category: "Accessories",
    stock: 150,
    brand: "SunnyStyle",
    isActive: true,
    targetAudience: "Women",
  },
  {
    name: "Men's Leather Wallet",
    description:
      "Slim leather wallet with multiple card slots and a coin pocket.",
    price: 29.99,
    slug: "mens-leather-wallet",
    isFeatured: true,
    image: "",
    category: "Accessories",
    stock: 80,
    brand: "LeatherCraft",
    isActive: true,
    targetAudience: "Men",
  },
  {
    name: "Men's Baseball Jacket",
    description:
      "Classic baseball jacket with ribbed cuffs and a snap-button closure.",
    price: 69.99,
    slug: "mens-baseball-jacket",
    isFeatured: true,
    image: "",
    category: "Clothes",
    stock: 110,
    brand: "SportStyle",
    isActive: true,
    targetAudience: "Men",
  },
  {
    name: "Women's Backpack",
    description:
      "Fashionable and spacious backpack with multiple compartments.",
    price: 39.99,
    slug: "womens-backpack",
    isFeatured: true,
    image: "",
    category: "Accessories",
    stock: 60,
    brand: "CityBag",
    isActive: true,
    targetAudience: "Women",
  },
  {
    name: "Men's Dress Shirt",
    description: "Classic fit dress shirt with a button-down collar.",
    price: 39.99,
    slug: "mens-dress-shirt",
    isFeatured: true,
    image: "",
    category: "Clothes",
    stock: 130,
    brand: "FormalWear",
    isActive: true,
    targetAudience: "Men",
  },
  {
    name: "Women's Pencil Skirt",
    description: "Tailored pencil skirt with a flattering silhouette.",
    price: 34.99,
    slug: "womens-pencil-skirt",
    isFeatured: false,
    image: "",
    category: "Clothes",
    stock: 90,
    brand: "Elegance",
    isActive: true,
    targetAudience: "Women",
  },
  {
    name: "Men's Flip Flops",
    description: "Comfortable flip-flops with cushioned footbed for easy wear.",
    price: 14.99,
    slug: "mens-flip-flops",
    isFeatured: false,
    image: "",
    category: "Footwear",
    stock: 220,
    brand: "BeachSteps",
    isActive: true,
    targetAudience: "Men",
  },
  {
    name: "Women's Sandals",
    description:
      "Stylish sandals with a comfortable sole and adjustable straps.",
    price: 24.99,
    slug: "womens-sandals",
    isFeatured: true,
    image: "",
    category: "Footwear",
    stock: 150,
    brand: "SummerVibe",
    isActive: true,
    targetAudience: "Women",
  },
  {
    name: "Men's Casual Watch",
    description: "Stylish watch with a leather strap and minimalistic design.",
    price: 89.99,
    slug: "mens-casual-watch",
    isFeatured: false,
    image: "",
    category: "Accessories",
    stock: 50,
    brand: "TimeX",
    isActive: true,
    targetAudience: "Men",
  },
  {
    name: "Women's Knee-High Boots",
    description: "Sleek knee-high boots with a pointed toe and a chunky heel.",
    price: 79.99,
    slug: "womens-knee-high-boots",
    isFeatured: true,
    image: "",
    category: "Footwear",
    stock: 70,
    brand: "BootStyle",
    isActive: true,
    targetAudience: "Women",
  },
  {
    name: "Men's Running Shorts",
    description: "Lightweight and breathable shorts perfect for running.",
    price: 24.99,
    slug: "mens-running-shorts",
    isFeatured: false,
    image: "",
    category: "Clothes",
    stock: 180,
    brand: "SportGear",
    isActive: true,
    targetAudience: "Men",
  },
  {
    name: "Women's Silk Scarf",
    description: "Luxurious silk scarf with a vibrant floral pattern.",
    price: 39.99,
    slug: "womens-silk-scarf",
    isFeatured: true,
    image: "",
    category: "Accessories",
    stock: 40,
    brand: "LuxeWear",
    isActive: true,
    targetAudience: "Women",
  },
  {
    name: "Men's Sports Backpack",
    description:
      "Durable backpack with multiple pockets, perfect for sports gear.",
    price: 49.99,
    slug: "mens-sports-backpack",
    isFeatured: true,
    image: "",
    category: "Accessories",
    stock: 60,
    brand: "SportPack",
    isActive: true,
    targetAudience: "Men",
  },
  {
    name: "Women's Statement Necklace",
    description: "Bold statement necklace with a mix of gold and silver tones.",
    price: 29.99,
    slug: "womens-statement-necklace",
    isFeatured: true,
    image: "",
    category: "Accessories",
    stock: 120,
    brand: "GlamourGold",
    isActive: true,
    targetAudience: "Women",
  },
  {
    name: "Men's Golf Polo Shirt",
    description:
      "Classic polo shirt designed for comfort and performance on the golf course.",
    price: 39.99,
    slug: "mens-golf-polo-shirt",
    isFeatured: false,
    image: "",
    category: "Clothes",
    stock: 150,
    brand: "EliteGolf",
    isActive: true,
    targetAudience: "Men",
  },
];
